/**:
  ros__parameters:
    additional_lidars: ["front_upper", "front_lower"]
    use_ransac_pipeline: False

    front_upper_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 30.0
        split_points_distance_tolerance: 0.1
        split_height_distance: 0.05

    front_lower_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 30.0
        split_points_distance_tolerance: 0.1
        split_height_distance: 0.05
