/**:
  ros__parameters:
    pull_out:
      enable_shift_pull_out: true
      enable_geometric_pull_out: true
      eable_back: false
      th_arrived_distance_m: 1.0
      th_stopped_velocity_mps: 0.01
      th_stopped_time_sec: 1.0
      collision_check_margin: 1.0
      pull_out_finish_judge_buffer: 1.0
      back_update_duration: 3.0
      # search start pose backward
      max_back_distance: 15.0
      backward_search_resolution: 2.0
      min_stop_distance: 2.0
      # geometric pull out
      geometric_pull_out_velocity: 1.0
      arc_path_interval: 1.0
      lane_departure_margin: 0.2
      backward_velocity: -1.0
      max_steer_rad: 0.26  # 15deg
      # shift pull out
      shift_pull_out_velocity: 2.0
      pull_out_sampling_num: 4
      before_pull_out_straight_distance: 5.0
      after_pull_out_straight_distance: 5.0
      maximum_lateral_jerk: 2.0
      minimum_lateral_jerk: 0.5
      deceleration_interval: 15.0
