/**:
  ros__parameters:
    lane_change:
      min_stop_distance: 5.0
      stop_time: 2.0
      hysteresis_buffer_distance: 2.0
      lane_change_prepare_duration: 4.0
      lane_changing_duration: 8.0
      lane_change_finish_judge_buffer: 3.0
      minimum_lane_change_velocity: 5.6
      prediction_duration: 8.0
      prediction_time_resolution: 0.5
      static_obstacle_velocity_thresh: 1.5
      maximum_deceleration: 1.0
      enable_abort_lane_change: true
      enable_collision_check_at_prepare_phase: true
      use_predicted_path_outside_lanelet: true
      use_all_predicted_path: true
      lane_change_sampling_num: 10
      enable_blocked_by_obstacle: false
      safety_time_margin_for_control: 2.0
      rear_vehicle_reaction_time: 1.0
      lateral_distance_threshold: 5.0
      expected_front_deceleration: -1.0
      expected_rear_deceleration: -1.0
      publish_debug_marker: true
