/**:
  ros__parameters:
    lane_change:
      lane_change_prepare_duration: 4.0
      lane_changing_duration: 8.0
      lane_change_finish_judge_buffer: 3.0
      minimum_lane_change_velocity: 5.6
      prediction_time_resolution: 0.5
      maximum_deceleration: 1.0
      enable_abort_lane_change: true
      enable_collision_check_at_prepare_phase: true
      use_predicted_path_outside_lanelet: true
      use_all_predicted_path: true
      lane_change_sampling_num: 10
      enable_blocked_by_obstacle: false
      publish_debug_marker: true
