/**:
  ros__parameters:
    lane_change:
      lane_change_prepare_duration: 4.0         # [s]
      lane_changing_safety_check_duration: 8.0  # [s]

      minimum_lane_change_prepare_distance: 2.0 # [m]
      minimum_lane_change_length: 16.5
      backward_length_buffer_for_end_of_lane: 2.0
      lane_change_finish_judge_buffer: 3.0      # [m]

      double lane_changing_lateral_jerk: 0.5
      double lane_changing_lateral_acc: 0.5

      minimum_lane_change_velocity: 2.78        # [m/s]
      prediction_time_resolution: 0.5           # [s]
      maximum_deceleration: 1.0                 # [m/s2]
      lane_change_sampling_num: 10

      # collision check
      enable_collision_check_at_prepare_phase: false
      prepare_phase_ignore_target_speed_thresh: 0.1 # [m/s]
      use_predicted_path_outside_lanelet: true
      use_all_predicted_path: true

      # abort
      enable_cancel_lane_change: true
      enable_abort_lane_change: true

      abort_lane_change_velocity_thresh: 0.5
      abort_lane_change_angle_thresh: 10.0      # [deg]
      abort_lane_change_distance_thresh: 0.3    # [m]
      prepare_phase_ignore_target_speed_thresh: 0.1 # [m/s]

      abort_lane_change_velocity_thresh: 0.5    # [m]
      abort_lane_change_angle_thresh: 0.174533  # [rad]
      abort_lane_change_distance_thresh: 0.3    # [m]

      abort_begin_min_longitudinal_thresh: 4.0  # [m]
      abort_begin_max_longitudinal_thresh: 6.0  # [m]
      abort_begin_duration: 3.0                 # [s]

      abort_return_min_longitudinal_thresh: 12.0 # [m]
      abort_return_max_longitudinal_thresh: 16.0 # [m]
      abort_return_duration: 6.0                 # [s]

      abort_expected_deceleration: 0.1           # [m/s2]
      abort_longitudinal_jerk: 0.5               # [m/s3]

      abort_max_lateral_jerk: 5.0                # [m/s3]

      # debug
      publish_debug_marker: false
