/**:
  ros__parameters:
    module_list:
      - "detection_area"
      - "lane_change_left"
      - "lane_change_right"

    default_enable_list:
      - "detection_area"
      - "lane_change_left"
      - "lane_change_right"
