/**:
  ros__parameters:
    publish_diag: true  # if true, diagnostic msg is published
    use_previous_trajectory_on_invalid: true # if true, invalid trajectory is not published, previous valid trajectory is published instead.
    display_on_terminal: true # show error msg on terminal
    thresholds:
      interval: 100.0
      relative_angle: 2.0  # (= 115 degree)
      curvature: 1.0
      lateral_acc: 9.8
      longitudinal_max_acc: 9.8
      longitudinal_min_acc: -9.8
      steering: 1.414
      steering_rate: 10.0
      velocity_deviation: 100.0
      distance_deviation: 100.0
