name: Build and test

on:
  pull_request:
    branches:
      - ros2
  push:
    branches:
      - ros2

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Clone dependency packages
      run: |
        mkdir dependency_ws
        vcs import dependency_ws < build_depends.repos

    - name: Install missing dependencies
      run: |
        sudo apt update
        rosdep update
        DEBIAN_FRONTEND=noninteractive rosdep install --from-paths . --ignore-src --rosdistro foxy -y
        sudo apt-get install -y \
          ros-foxy-tf2>=0.13.6-1focal.20201028.172335 \
          ros-foxy-tf2-geometry-msgs>=0.13.6-1focal.20201028.172335 \
          ros-foxy-tf2-ros>=0.13.6-1focal.20201028.172335 \
          ros-foxy-tf2-sensor-msgs>=0.13.6-1focal.20201028.172335

    - name: Build
      run: |
        . /opt/ros/foxy/setup.sh
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        . /opt/ros/foxy/setup.sh
        colcon test \
          --event-handlers console_cohesion+ \
          --return-code-on-test-failure
